matrix:
  include:
  - language: node_js
    node_js:
    - '8'
    if: branch = master
    branches:
      only:
      - master
    cache:
      yarn: true
addons:
  ssh_known_hosts: 200.19.32.125      
before_install:
- openssl aes-256-cbc -K $encrypted_70d65a9ff61c_key -iv $encrypted_70d65a9ff61c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master